### ISSUE TITLE
Updating latest dependencies

### ISSUE THREAD

**Issue by sbiaudet** [pjvds/ncqrs#106]
Dependencies are outdated. Updating to latest versions.

**Comment by kadamgreene** [comment]
Hi @sbiaudet, 

There is an issue with XUnit, in that it runs multiple tests in parallel which can result in unexpected behaviour (tests failing because the NcqrsEnvironment was altered in parallel by another test).

To fix this problem you need to add:

`[assembly: CollectionBehavior(CollectionBehavior.CollectionPerAssembly)]`

To the Test projects to keep things sane.
